# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doques',
            fields=[
                ('run_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('answ_content', models.CharField(max_length=1000)),
                ('memory', models.CharField(max_length=10)),
                ('language_type', models.CharField(max_length=2)),
                ('result_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ques_type', models.CharField(max_length=10)),
                ('ques_title', models.CharField(max_length=200)),
                ('ques_content', models.CharField(max_length=800)),
                ('answer', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=2)),
                ('passnum', models.CharField(max_length=6)),
                ('totalnum', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=2)),
                ('school', models.CharField(max_length=5)),
                ('faculties', models.CharField(max_length=6)),
                ('cls', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='doques',
            name='someone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqltrainapp.User'),
        ),
        migrations.AddField(
            model_name='doques',
            name='someques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqltrainapp.Question'),
        ),
    ]
